<a href="https://colab.research.google.com/github/dinesh842/python-/blob/main/Copy_of_Untitled19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np


In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(3,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(3, 3)

In [ ]:
b.dtype

dtype('int64')

In [ ]:
# we have a list
lst_1=[i for i in range(10)]
lst_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#to add value 2 to all the elements
#1)  normal method
# lst_2=[]
# for item in lst_1:
#       list_2.append(item+2)
# print(lst_2)

#2) list comprehension
lst_2=[i+2 for i in lst_1]
print(lst_2)


[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a=np.array([[2,3] ,[2,4],[8,9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [ ]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((5,3),3.3)

array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [ ]:
np.full((2,4),3.3)

array([[3.3, 3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3, 3.3]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([2,5,68,78])

array([[ 2,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 68,  0],
       [ 0,  0,  0, 78]])

In [ ]:
a=np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
a[0]

2

In [ ]:
a[2]

6

In [ ]:
a[-1]

16

In [ ]:
# accessing multiple elements 
a[[0,2,4]]

array([ 2,  6, 10])

In [ ]:
# slicing
# to get all the elements from 2nd index
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
# to get all the alternate elements
a[::2]

array([ 2,  6, 10, 14])

In [ ]:
# consider we have 2D array
a= np.array([[0,1,2,3] ,[4,5,6,7],[8,9,10,11],[12,13,14,15]])